export const transactions = [
    {
        id: 1,
        img: "user-avatar.jpg",
        name: "customer 1",
        platform: "wooCommerce",
        value: "149.99",
    },
    {
        id: 2,
        img: "user-avatar.jpg",
        name: "customer 2",
        platform: "Amazon",
        value: "49.99",
    },
    {
        id: 3,
        img: "user-avatar.jpg",
        name: "customer 3",
        platform: "Ebay",
        value: "199.99",
    },
    {
        id: 4,
        img: "user-avatar.jpg",
        name: "customer 4",
        platform: "Shopify",
        value: "9.99",
    },
    {
        id: 5,
        img: "user-avatar.jpg",
        name: "customer 5",
        platform: "Hepsiburada",
        value: "1149.99",
    },
    {
        id: 6,
        img: "user-avatar.jpg",
        name: "customer 6",
        platform: "Shopify",
        value: "209.99",
    },
    {
        id: 7,
        img: "user-avatar.jpg",
        name: "customer 7",
        platform: "wooCommerce",
        value: "349.99",
    },
]