export const leadData = {
  color: "#8884d8",
  icon: "/userIcon.svg",
  title:"Gained Leads",
  dataKey:"val",
  rate:41,
  span: "Week",
  datas: [
    {name: "Sun", val: 120},
    {name: "Mon", val: 176},
    {name: "Tue", val: 133},
    {name: "Wed", val: 87},
    {name: "Thu", val: 54},
    {name: "Fri", val: 90},
    {name: "Sat", val: 112},
  ],
};
export const salesData = {
  color: "skyblue",
  icon: "/productIcon.svg",
  title:"Total sales",
  dataKey:"val",
  rate:13,
  span: "Week",
  datas: [
    {name: "Sun", val: 20},
    {name: "Mon", val: 76},
    {name: "Tue", val: 33},
    {name: "Wed", val: 87},
    {name: "Thu", val: 54},
    {name: "Fri", val: 90},
    {name: "Sat", val: 42},
  ],
};
export const orderData = {
  color: "teal",
  icon: "/revenueIcon.svg",
  title:"Average Order",
  dataKey:"val",
  rate:-5,
  span: "Week",
  datas: [
    {name: "Sun", val: 49},
    {name: "Mon", val: 38},
    {name: "Tue", val: 33},
    {name: "Wed", val: 80},
    {name: "Thu", val: 21},
    {name: "Fri", val: 35},
    {name: "Sat", val: 42},
  ],
};
export const marketingData = {
  color: "gold",
  icon: "/conversionIcon.svg",
  title:"Marketing Interactions",
  dataKey:"val",
  rate:4,
  span: "Week",
  datas: [
    {name: "Sun", val: 220},
    {name: "Mon", val: 176},
    {name: "Tue", val: 133},
    {name: "Wed", val: 187},
    {name: "Thu", val: 154},
    {name: "Fri", val: 190},
    {name: "Sat", val: 142},
  ],
};
export const profileData = {
  color: "#8884d8",
  icon: "/userIcon.svg",
  title:"Total Profit",
  dataKey:"val",
  rate:32,
  span: "Year",
  datas: [
    {name: "January", val: 120},
    {name: "February", val: 176},
    {name: "March", val: 133},
    {name: "April", val: 87},
    {name: "May", val: 54},
    {name: "June", val: 90},
    {name: "July", val: 112},
    {name: "August", val: 120},
    {name: "September", val: 176},
    {name: "October", val: 133},
    {name: "November", val: 54},
    {name: "December", val: 87},
    
  ],
};